pipeline {
    agent any

    stages {
       stage('Checkout') {
                  steps {
                      script {
                          // Specify your Git repository URL
                          def gitRepoUrl = 'https://github.com/dahalrr16/springbook.git'

                          // Checkout the repository and switch to the desired branch or commit
                          checkout([$class: 'GitSCM', branches: [[name: 'master']], userRemoteConfigs: [[url: gitRepoUrl]]])
                      }
                  }
              }

        stage('Build') {
            steps {
                script {
                    // Build the Spring Boot application
                    sh 'cd ./springbook && mvn clean package'
                //  sh 'cd ./springbook && mvn clean package && mvn spring-boot:run'
                }
            }
        }

          stage('Deploy') {
            steps {
                script {
                    echo 'Deploy the Spring Boot application'
                sh 'pwd && java -jar /var/lib/jenkins/workspace/AP111111-infra-springbook/springbook/target/springbook-0.0.1-SNAPSHOT.jar'
                //  sh 'cd ./springbook && mvn clean package && mvn spring-boot:run'
                }
            }
        }


   
    }

    post {
        success {
            echo 'Pipeline succeeded!'

            // Optionally, deploy your application or perform additional steps
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}
